language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm install
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    app: sayaradz-frontend
    secure: RIkHYtbFVZMii8CS9JFcdRn4I5YMn94h8HycdN6HsOVGWQrAo8hdL59DEmxgsrpSKpbfHqLmE+sNxzIgfNeu9fojJJFchjXjX2uxLT08pwW3NX4VkHdxtz3DgnQZP+jYRFOmxx8WbO3fOB731+svCoE5DQptBw85hjGGaGn7SNYqnAPkC5H5xvM6jUkwuW4w34LYFqlTWVS5quvYH6hK2/8tY+wVyiDnvmy1YeAuBNb1eyWIhousYURDM/ybtxEAihVPdzOt/KEzWNkCtx5FW+cmGa6Dj23NC/vMVygtgTCRb2sIINZOvnqaEDusQYvZl2jYMcnrbkRd3jYELEHts/5aLie1BE8WuuvTpV+dUQuSZnrmOSRx1ZDT3QhsrhxdIAUuFyG/EvbQiGs9RpOKtGoUu6Tkm8v1yJhCErelQ5TmHK/3qCVyVqE/RY/dCfhjuDnJha+KaO5WP7CoxjHruMcONIhGXBVfTPHLtuhsZimpxlvjxHMnUl1V5mXby26oIRbje6Mh8KLsFcSnlGVq7elfxKCgQxAW83Q3GqMC89PNLgyrWmhbecyxBMAWZJgHobbr8rADa0ehscWLaYjTzzefYlDQ2P1P+/0lfTEw7gqV51ZANzQaaQQ+CWP7oFoQFELQmRBz0f7anQcR9dBpvlGjaOtxYMd2DJq1yFeZbMk=
notifications:
  email: false
  slack:
    secure: TUOXVnueSshYgSL8D47Kr5zkSCDXg0C8rf9Eyp8bZC8bJ6sm/xEguCUfgZUObAAU5sAa+I1ZGgFw1RDOZunQDC7nvtd2XFCFPiPXUzdtqJ9DOGhU9mStGNNVVKCoQ/ga7BjEtf8F21Jo0BS+sy14i3bJYoQUpl9Z2QlVUbmtc6L/8yiKmFSTCZDOWOUuVg2ZsWpqMmouM/CwVHPrUCkknMRxno63MQtrUY4t+OALpcEXDSeeIYmshtF4Adsw6z0J/GHitcCOStpcBAz61fK19xNb6w3ofy8y3AVm3+Z0FaN3ZjjtapXKk0QsdiCxA5R42PSklF4cYjGtMAukqaonxVSIHEux0l3Rw7+r1M2oXwyAF23q+EHmGEqHmZiACQlgsCC80xrKzk2f2O7JkE4tuRv7uwniKkO00IVTZ9QetLYjLYiX+Zvbw1LeWJSTLZjIPEQViem+2OVE/51jAixP3+JipCClgQSjfIFV6L3j+93vA+SgEzID5XUOObD2d4bpnIoPx6XaLUM1tsPxfQvmTKPQ2jY84VPaL28bxMr/mCKBsxXi2Vvf0MqtFWV9DTZprhrHCD1LzlREZ1A59qa0RWitiGN7WVJCfAvz/UXe2qnFm+vfHt8tS+i/p6mT7fuPUSsyy3ZAhNt57HP+82F0KBkU4289atcbB6/nxErmkZ0=
