language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    app: sayaradz-frontend
    secure: RIkHYtbFVZMii8CS9JFcdRn4I5YMn94h8HycdN6HsOVGWQrAo8hdL59DEmxgsrpSKpbfHqLmE+sNxzIgfNeu9fojJJFchjXjX2uxLT08pwW3NX4VkHdxtz3DgnQZP+jYRFOmxx8WbO3fOB731+svCoE5DQptBw85hjGGaGn7SNYqnAPkC5H5xvM6jUkwuW4w34LYFqlTWVS5quvYH6hK2/8tY+wVyiDnvmy1YeAuBNb1eyWIhousYURDM/ybtxEAihVPdzOt/KEzWNkCtx5FW+cmGa6Dj23NC/vMVygtgTCRb2sIINZOvnqaEDusQYvZl2jYMcnrbkRd3jYELEHts/5aLie1BE8WuuvTpV+dUQuSZnrmOSRx1ZDT3QhsrhxdIAUuFyG/EvbQiGs9RpOKtGoUu6Tkm8v1yJhCErelQ5TmHK/3qCVyVqE/RY/dCfhjuDnJha+KaO5WP7CoxjHruMcONIhGXBVfTPHLtuhsZimpxlvjxHMnUl1V5mXby26oIRbje6Mh8KLsFcSnlGVq7elfxKCgQxAW83Q3GqMC89PNLgyrWmhbecyxBMAWZJgHobbr8rADa0ehscWLaYjTzzefYlDQ2P1P+/0lfTEw7gqV51ZANzQaaQQ+CWP7oFoQFELQmRBz0f7anQcR9dBpvlGjaOtxYMd2DJq1yFeZbMk=
notifications:
  email: false
  slack:
    secure: wS/rakWlWCwRRZozPhUJt7vejz3xTd91yTw4hfwsiwt0lMvHDihcm9f00wLK+uJVI6lGytQ0U7aqkYTWnG778tCTpY2Mdp3CrAB6e2rhQ78+wHV+ouegQHbIwM0oeU/t4qR0pQSTYIZ2lTCtNNWsq3JYktceaYd53Co1zpJPgWUNA8meU3Rm6z2qzILb/O4o3a4seoIY5FAQDMCxPspW47DVvgU5O1qFlimmQDNuEdzIcbjY9U1bMuDOa0GIbgJhbMBKCOHOf7Z6Q0rt0cyJ0Ows/lNN3a7Mh1EznxfrJqUwAfFnTR/o86fInA3I2RQj2ROYYZL3GHe8Ymoh5nQPu6tzN9VFSDBglA5In4ewLBg1oDYxILlieQfViIsA1AmU8sUY7AdrzXcUauUCHqCVM6UqKMJuBvVN4BKCc+5168r/CxxlEvIJ531auzUty4VkxuhJwnqKobXrkT9EEQWYCVrmbEAO+tbH6Z6zBRn1wBtoI8svZBNyVNfnsbCKK4RNBmc9cDGm5/jaDUegeQLf/2CRKiNLLjg4WjbJw7Uz/YjJrM1r/9qyyBEX7lWrM5NIr7GB/75NkW3LZ62Hmdy1R5UMClhLadCwiYBJH280i8tQvG46UkScbsPh3mxalNB9/McC3WI6ROFiVbWXyk7ga9R5yMl9/Jgf/HzgXzT2tZY=
